### ISSUE TITLE
Warning appears in R console when widget renders

### ISSUE THREAD

**Issue by bzkrouse** [ASA-DIA-InteractiveSafetyGraphics/ReDish#2]
The following warning appears in console, but doesn't seem to interfere with widget rendering. Have tried adding blank trailing line to yaml file.

> library(ReDish)
> eDISH(data = adlbc)

Warning message:
In readLines(con) :
  incomplete final line found on 'C:/Program Files/R/R-3.5.1/library/ReDish/htmlwidgets/eDISH.yaml'

**Comment by jwildfire** [comment]
Check this out: https://support.rstudio.com/hc/en-us/community/posts/200641498--incomplete-final-line-found-warning
