### ISSUE TITLE
Widget does not appear in RStudio viewer in windows

### ISSUE THREAD

**Issue by bzkrouse** [ASA-DIA-InteractiveSafetyGraphics/ReDish#4]
Potentially related to OS.  Widget rendered in viewer on 2 Macs with different amounts of memory, but did not render on 2 different Windows systems.

**Comment by jwildfire** [comment]
This is now fixed in using the bleeding edge version of `safety-eDish`. Once v0.13 of the javascript library is released, we can update here and close this out.
